language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - sudo apt-get install -qq libprotobuf-dev libzmq3-dev protobuf-compiler
    - git submodule update --init --recursive
    - pip install -r requirements.txt
    - pip install -e .
script: nosetests
